// casos/lista-filtravel/react/src/main.tsx
import { useState } from "react";
import { createRoot } from "react-dom/client";
import {
  categorias,
  comparador,
  correspondeABusca,
  daCategoria,
  formatarPreco,
  ordens,
  produtos,
  textoDaContagem,
  type Ordem,
} from "../../dominio";
import "../../estilo.css";

function CatalogoDeProdutos() {
  const [busca, setBusca] = useState("");
  const [categoria, setCategoria] = useState("");
  const [ordem, setOrdem] = useState<Ordem>("nome");

  // A lista visível é derivada do estado a cada renderização.
  const visiveis = produtos
    .filter((produto) => correspondeABusca(produto, busca) && daCategoria(produto, categoria))
    .sort(comparador(ordem));

  return (
    <main className="catalogo">
      <div className="filtros">
        <label>
          Buscar
          <input
            name="busca"
            type="search"
            placeholder="Nome do produto"
            value={busca}
            onChange={(e) => setBusca(e.target.value)}
          />
        </label>
        <label>
          Categoria
          <select name="categoria" value={categoria} onChange={(e) => setCategoria(e.target.value)}>
            <option value="">Todas</option>
            {categorias.map((c) => (
              <option key={c} value={c}>
                {c}
              </option>
            ))}
          </select>
        </label>
        <label>
          Ordenar por
          <select name="ordem" value={ordem} onChange={(e) => setOrdem(e.target.value as Ordem)}>
            {ordens.map((o) => (
              <option key={o.valor} value={o.valor}>
                {o.rotulo}
              </option>
            ))}
          </select>
        </label>
      </div>
      <p className="contagem" role="status">
        {textoDaContagem(visiveis.length)}
      </p>
      <ul className="produtos">
        {visiveis.map((produto) => (
          <li key={produto.id}>
            <span className="nome">{produto.nome}</span>
            <span className="categoria">{produto.categoria}</span>
            <span className="preco">{formatarPreco(produto.preco)}</span>
          </li>
        ))}
      </ul>
      {visiveis.length === 0 && <p className="vazio">Nenhum produto encontrado.</p>}
    </main>
  );
}

createRoot(document.getElementById("raiz")!).render(<CatalogoDeProdutos />);

// casos/lista-filtravel/web-component/src/main.ts
import {
  categorias,
  comparador,
  correspondeABusca,
  daCategoria,
  formatarPreco,
  ordens,
  produtos,
  textoDaContagem,
  type Ordem,
  type Produto,
} from "../../dominio";
import "../../estilo.css";

const modelo = `
  <main class="catalogo">
    <div class="filtros">
      <label>
        Buscar
        <input name="busca" type="search" placeholder="Nome do produto" />
      </label>
      <label>
        Categoria
        <select name="categoria">
          <option value="">Todas</option>
        </select>
      </label>
      <label>
        Ordenar por
        <select name="ordem"></select>
      </label>
    </div>
    <p class="contagem" role="status"></p>
    <ul class="produtos"></ul>
    <p class="vazio" hidden>Nenhum produto encontrado.</p>
  </main>
`;

class CatalogoDeProdutos extends HTMLElement {
  private busca!: HTMLInputElement;
  private categoria!: HTMLSelectElement;
  private ordem!: HTMLSelectElement;
  private contagem!: HTMLParagraphElement;
  private lista!: HTMLUListElement;
  private vazio!: HTMLParagraphElement;

  connectedCallback() {
    this.innerHTML = modelo;
    this.busca = this.querySelector('[name="busca"]')!;
    this.categoria = this.querySelector('[name="categoria"]')!;
    this.ordem = this.querySelector('[name="ordem"]')!;
    this.contagem = this.querySelector(".contagem")!;
    this.lista = this.querySelector(".produtos")!;
    this.vazio = this.querySelector(".vazio")!;

    for (const categoria of categorias) {
      this.categoria.append(new Option(categoria, categoria));
    }
    for (const ordem of ordens) {
      this.ordem.append(new Option(ordem.rotulo, ordem.valor));
    }

    this.busca.addEventListener("input", () => this.atualizarLista());
    this.categoria.addEventListener("change", () => this.atualizarLista());
    this.ordem.addEventListener("change", () => this.atualizarLista());

    this.atualizarLista();
  }

  // Refaz a lista inteira a cada mudança num dos controles.
  private atualizarLista() {
    const visiveis = produtos
      .filter(
        (produto) =>
          correspondeABusca(produto, this.busca.value) &&
          daCategoria(produto, this.categoria.value),
      )
      .sort(comparador(this.ordem.value as Ordem));

    this.lista.replaceChildren(...visiveis.map((produto) => this.criarItem(produto)));
    this.contagem.textContent = textoDaContagem(visiveis.length);
    this.vazio.hidden = visiveis.length > 0;
  }

  private criarItem(produto: Produto): HTMLLIElement {
    const item = document.createElement("li");
    const nome = document.createElement("span");
    const categoria = document.createElement("span");
    const preco = document.createElement("span");
    nome.className = "nome";
    categoria.className = "categoria";
    preco.className = "preco";
    nome.textContent = produto.nome;
    categoria.textContent = produto.categoria;
    preco.textContent = formatarPreco(produto.preco);
    item.append(nome, categoria, preco);
    return item;
  }
}

customElements.define("catalogo-de-produtos", CatalogoDeProdutos);
